CREATE TABLE token_user (id bigint generated BY DEFAULT AS IDENTITY, login VARCHAR(255), password VARCHAR(255), role VARCHAR(255), PRIMARY KEY (id));

ALTER TABLE token_user
ADD CONSTRAINT unique_login UNIQUE (login);