CREATE TABLE roles (id bigint generated by default as identity, role_name varchar(255), primary key (id));
create table user_role (role_id bigint not null, user_id bigint not null, primary key (role_id, user_id));
create table users (id bigint generated by default as identity, email varchar(255), login varchar(255) unique, password varchar(255), primary key (id));

alter table if exists user_role add constraint FKt7e7djp752sqn6w22i6ocqy6q foreign key (role_id) references roles;
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users;